apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tearenvd-environments
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "create", "patch"]
  - apiGroups: [""]
    resources: ["configmaps", "persistentvolumeclaims", "secrets", "serviceaccounts", "services"]
    verbs: ["get", "create", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["get", "create", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments/scale", "statefulsets/scale"]
    verbs: ["get", "update"]
  - apiGroups: ["batch"]
    resources: ["cronjobs", "jobs"]
    verbs: ["get", "create", "patch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses", "networkpolicies"]
    verbs: ["get", "create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tearenvd-environments
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tearenvd-environments
subjects:
  - kind: ServiceAccount
    name: tearenvd
    namespace: tearenv-system
