apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - persistentvolumeclaim.yaml
  - role.yaml
  - rolebinding.yaml
  - service.yaml
  - registration-service.yaml
  - metrics-service.yaml
  - serviceaccount.yaml

labels:
  - pairs:
      app.kubernetes.io/name: tearenv
      app.kubernetes.io/component: gateway
    includeSelectors: true
