apiVersion: v1
kind: Service
metadata:
  name: tearenvd
spec:
  type: ClusterIP
  ports:
    - name: ssh
      port: 2222
      targetPort: ssh
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: metrics
      protocol: TCP
