apiVersion: v1
kind: Service
metadata:
  name: {{ include "tearenv.fullname" . }}-registration
  labels:
    {{- include "tearenv.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.registration.port }}
      targetPort: registration
      protocol: TCP
  selector:
    {{- include "tearenv.selectorLabels" . | nindent 4 }}
