{{- if not .Values.bootstrap.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tearenv.bootstrapSecretName" . }}
  labels:
    {{- include "tearenv.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.bootstrap.secretKey }}: |
    {{- .Values.bootstrap.policy | nindent 4 }}
{{- end }}
