{{- if not .Values.bootstrap.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tearenv.bootstrapSecretName" . }}
  labels:
    {{- include "tearenv.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.bootstrap.secretKey }}: |
    {{- .Values.bootstrap.policy | nindent 4 }}
{{- end }}
{{- if and (eq .Values.registration.authMode "token") (not .Values.registration.token.existingSecret) }}
{{- $secretName := include "tearenv.registrationSecretName" . }}
{{- $token := randAlphaNum 48 }}
{{- with (lookup "v1" "Secret" .Release.Namespace $secretName) }}
{{- $token = (index .data $.Values.registration.token.secretKey | b64dec) }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "tearenv.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  {{ .Values.registration.token.secretKey }}: {{ $token | b64enc | quote }}
{{- end }}
