apiVersion: v1
kind: Service
metadata:
  name: {{ include "tearenv.fullname" . }}
  labels:
    {{- include "tearenv.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: ssh
      port: {{ .Values.service.port }}
      targetPort: ssh
      protocol: TCP
  selector:
    {{- include "tearenv.selectorLabels" . | nindent 4 }}
